name: Testar Anexos de Issues

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Baixar e extrair o anexo da issue
      run: |
        # Obter URL do anexo
        attachment_url=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH" | grep -Eo 'https://[^ ]+')
        if [[ -n "$attachment_url" ]]; then
          curl -L -o projeto.zip "$attachment_url"
          unzip projeto.zip -d projeto
        else
          echo "Nenhum anexo encontrado na issue."
          exit 1
        fi

    - name: Entrar na pasta do projeto
      run: cd projeto

    - name: Instalar dependências
      run: |
        cd projeto
        ./mvnw install -DskipTests
    
    - name: Análise Estática do Código
      run: |
        cd projeto
        ./mvnw checkstyle:check

    - name: Executar testes
      run: |
        cd projeto
        ./mvnw test

    - name: Gerar Relatório de Cobertura de Testes
      run: |
        cd projeto
        ./mvnw jacoco:report
    
    - name: Publicar resultados dos testes
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: result-logs
        path: projeto/target/surefire-reports

    - name: Publicar Relatório de Cobertura
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: projeto/target/site/jacoco
